on:
  push:
  release:
    types: [released]

env:
  VERSION: ${{ github.event_name == 'release' && github.ref_name || format('{0}-{1}', github.ref_name, github.run_number) }}

jobs:
  build:
    strategy:
      matrix:
        platform: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '^1.20.6'
    - name: build
      run: GOARCH=${{ matrix.platform }} make module.tar.gz
    - uses: actions/upload-artifact@v3
      with:
        name: binary-${{ matrix.platform }}
        path: module.tar.gz
  upload:
    # if: github.event_name == 'release'
    needs: [build]
    # todo: remove concurrency group once APP-2549 is fixed
    concurrency: no-simultaneous-upload-${{ github.ref_name }}-${{ github.run_number }}
    strategy:
      matrix:
        platform: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: binary-${{ matrix.platform }}
    - uses: viamrobotics/upload-module@main
      if: github.event_name == 'release'
      with:
        module-path: module.tar.gz
        platform: linux/${{ matrix.platform }}
        version: ${{ env.VERSION }}
        cli-config-secret: ${{ secrets.cli_config }}
